version: '{build}'
image:
  - Visual Studio 2019
  - Ubuntu
skip_commits:
  files:
    - '*.md'
    - '*.txt'
branches:
  only:
    - master
  except:
    - /.+[\-.]wip$/
    - wip
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
install:
  - cmd: curl -OsSL https://dot.net/v1/dotnet-install.ps1
  - ps: if ($isWindows) { ./dotnet-install.ps1 -JsonFile global.json }
  - sh: curl -OsSL https://dot.net/v1/dotnet-install.sh
  - sh: chmod +x dotnet-install.sh
  - sh: ./dotnet-install.sh --jsonfile global.json
  - sh: export PATH="$HOME/.dotnet:$PATH"
before_build:
- dotnet --info
build_script:
- ps: |-
    if ($isWindows) {
      $env:RID = 'win-x64'
    }
    elseif ($isLinux) {
      $env:RID = 'linux-x64'
    }
    else {
      throw 'Unsupported platform'
    }
- ps: dotnet publish -c Release -o dist/fdd
- ps: dotnet publish -c Release -o dist/scd          -r $RID
- ps: dotnet publish -c Release -o dist/one          -r $RID /p:PublishSingleFile=true
- ps: dotnet publish -c Release -o dist/one+trim     -r $RID /p:PublishSingleFile=true /p:PublishTrimmed=true
- ps: dotnet publish -c Release -o dist/one+trim+rtr -r $RID /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true /p:PublishReadyToRunShowWarnings=true
after_build:
- ps: |-
    if ($isWindows) {
      dir -Directory dist |
        % {
          pushd $_.FullName
          if ($isWindows) {
            7z.exe a "..\..\splitcsv-1.2-ubuntu-18.04-x64-$($_.Name).zip" *
          }
          elseif ($isLinux) {
            tar -vczf ../../splitcsv-1.2-win-x64-$d.tar.gz .
          }
          popd
        }
    }
artifacts:

  - path: splitcsv-*.tar.gz

  - path: splitcsv-*.zip

notifications:
- provider: Email
  to:
  - raboof-ci@googlegroups.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
