// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Fri, 13 Apr 2018 07:54:00 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.21913.0")]
[assembly: AssemblyFileVersion("1.0.21913.754")]
