// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Fri, 13 Apr 2018 08:19:55 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.1.21913.0")]
[assembly: AssemblyFileVersion("1.1.21913.819")]
